#
# Makefile for kernel RdLib BAL.
#

obj-m					+= irq_poll.o

#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

ccflags-y := -I$(src)/include
